### ISSUE TITLE
Enable SSl Issue 

### ISSUE THREAD

**Issue by iThink32** [mongodb/mongo-swift-driver#141]
I am currently using version 0.0.7 as I saw it in ur releases. I am able to connect and fetch a document from the mlab db but am not able to print the result or access it.

the error that I am getting is 

```
DEBUG:      cluster: Authentication failed: The SCRAM_SHA_1 authentication mechanism requires libmongoc built with ENABLE_SSL
```

**Comment by mbroadst** [comment]
Hi @iThink32, can you provide more information about where you are using the driver? Specifically, what operating system, how have you installed libmongoc, what version libmongoc is installed, etc. Thank you!

**Comment by iThink32** [comment]
@mbroadst I'm using this driver on iOS , on a simulator having a version of 12.0.I did not have to install libmongoc as this version of pod internally adds a mongo-embedded-c-driver folder as a dependancy.This directory contains the mongoc framework having a version of 1.13.0

**Comment by acmorrow** [comment]
The build of the C driver contained in mongo-embedded-c-driver has SSL disabled, because the C drivers native crypto layer doesn't currently build on iOS. Since mongo-embedded-c-driver was envisioned as primarily being used to talk to the embedded server, not a remote server, when deployed on iOS, this was not seen as a problem. In general, our expectation was that mobile applications would not be directly talking to remote databases, but instead to remote app servers that sat in front of a database. So it would be interesting if you could share some additional information on your use case.

We will attempt to get this issue addressed in an upcoming release. The ticket to track is https://jira.mongodb.org/browse/CDRIVER-2850.

**Comment by acmorrow** [comment]
@iThink32 - Well, the fastest way to see this fixed is for https://jira.mongodb.org/browse/CDRIVER-2850 to get fixed, and then we can re-enable SSL in the mongo-embedded-c-driver cocoapod. I think you should definitely reach out on that JIRA ticket and vote for it along with an explanation of why you need it fixed. If C programming on iOS is something you are familiar with and you feel comfortable working with the C driver source, submitting a pull request against the C driver (https://github.com/mongodb/mongo-c-driver) with a fix for the issue is probably the fastest way to see it fixed.

If you are interested in knowing more about how to do a cross compile of the C driver for iOS, you can work from the MongoDB build automation, available here:

- https://github.com/mongodb/mongo/blob/master/etc/evergreen.yml#L3753-L3821
- https://github.com/mongodb/mongo/blob/master/etc/evergreen.yml#L11165-L11177
- https://github.com/mongodb/mongo/blob/master/etc/evergreen.yml#L11197-L11209

What you are looking to do is synthesize a CMake invocation from those flags, but where you are replacing {{-DENABLE_SSL=OFF}} with {{-DENABLE_SSL=DARWIN}} and then get the C driver build to work that way.

**Comment by iThink32** [comment]
@acmorrow thanks for the feedback , I will comment on the ticket so that it gets picked up faster.

**Comment by iThink32** [comment]
@acmorrow not able to add a comment in the link you specified , please pass on my use case.

**Comment by jmikola** [comment]
@iThink32: This GitHub issue has been linked to [CDRIVER-2850](https://jira.mongodb.org/browse/CDRIVER-2850).
