### ISSUE TITLE
MongoError.commandError is too generic

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#200]
As it stands `MongoError.commandError` gives back only a `message: String`.
It would be really helpful if there could be an additional enum containing all the different errors codes translated to something meaningful.

Consider trying to insert a document with a duplicated id on a unique index this is what comes back from the driver:

>commandError(message: "E11000 duplicate key error collection: test index: myId_1 dup key: { : \"1ED542F9-8C36-44F9-8207-6F2DA290B3F3\" }")

The end goal for a backend service would be to return a HTTP status code of `409 Conflict` in this situation, with optionally more information about the error.

As it stands, the only way to do this is to parse the string, for the MongoDB error code `E11000 `.

It feels like it should be the driver responsibility to provide better error information.

**Comment by valeriomazzeo** [comment]
After having a look at the driver implementation it seems that in this particular case `commandError` is inappropriately used:

From `MongoCollection+Write.swift` line 25:
```swift
guard mongoc_collection_insert_one(self._collection, document.data, opts?.data, nil, &error) else {
            // TODO SWIFT-139: include writeErrors and writeConcernErrors from reply in the error
            throw MongoError.commandError(message: toErrorString(error))
        }
```

**Comment by patrickfreed** [comment]
You're absolutely right about this, and, as it turns out, we're in the process of restructuring how we handle errors. This PR (#183) introduced the new errors; check the description of it for an explanation of the new types. A PR in progress (#197) specifically handles the issues you mention here, and #199 / #198 update other errors.

You can track the progress of the task as a whole on our [jira project](https://jira.mongodb.org/browse/SWIFT-145).

As an example, with the new errors you could do the following:
```
do {
    try coll.insertOne(...)
} catch let ServerError.writeError(writeError, wcError, errLabels) {
    if writeError?.code == 11000 {
         // duplicate key error
    }
}

**Comment by kmahar** [comment]
closing as #197 has been merged. new error types along with an error handling guide (see #205) will be included in our next release 🙂
