### ISSUE TITLE
UUID does not conform to BSONValue

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#207]
I was a bit surprised to find out I cannot encode `UUID` objects directly because they don't conform to `BSONValue`.

Is this intended?

See example:
![screenshot 2019-02-08 at 15 08 19](https://user-images.githubusercontent.com/1882080/52486680-a8a47000-2bb3-11e9-92fb-34a1c3ef4d8a.png)

**Comment by patrickfreed** [comment]
We originally planned to conform `UUID` to `BSONValue`, but decided not to because it would create an asymmetry between what you put into a document and what you read from it. e.g. If you created a document of the form `["uuid": UUID()]`, then `doc["uuid"]` would return `Binary(...)`.

To avoid this asymmetry, we could separate our `Binary` into different types based on subtype, but there is no precedent for that in other drivers nor is it suggested in any of the MongoDB driver specifications, so we decided against it. 

You can still easily insert / read `Binary`s into / from your documents by doing:
```
let uuid = UUID()
let doc: Document = try ["uuid": Binary(from: uuid))
let binary = doc["uuid"] as! Binary
let uuid1 = try UUID(from: binary)
```
Also, `BSONEncoder` / `BSONDecoder` can still be used to store and retrieve `UUID` fields without any manual conversion.

**Comment by patrickfreed** [comment]
If you have any more questions, please let us know.

**Comment by valeriomazzeo** [comment]
I finally had time to look at this one again. The issue was that I have a method to encode primitive types using the BSONEncoder:

```swift
public func encodeBSONValue<T: Encodable>(_ value: T) throws -> BSONValue {
        switch value {
        case let value as BSONValue:
            return value
        default:
            // We can only use BSONEncoder to encode top-level data
            let wrappedData = ["value": value]
            let document: Document = try self.encode(wrappedData)

            return document["value"] ?? BSONNull()
        }
    }
```

As you can see, there's a short-circuit allowing `BSONValue`s to skip the encoding.
The problem happens when passing an `Array of UUIDs` because `Array` is a `BSONValue` regardless of its `Element` type.

Perhaps since Swift 4.2 conditional conformance could be added `where Element: BSONValue`?

**Comment by patrickfreed** [comment]
Yep, you're exactly right. We plan to use conditional conformance as you suggest once we drop support for Swift 4.0. You can track the progress on that [here](https://jira.mongodb.org/browse/SWIFT-215).
