### ISSUE TITLE
bson_malloc memory leak

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#236]
Hi, there. 
I am experiencing massive memory leaks that seems to originate from `bson_malloc`.
These calls are possibly originated by `BSONDecoder`.
Running on macOS 10.14.4 / mongo driver 0.0.9 /  mongo-c-driver 1.13.0

Would be grateful if someone could help debugging the issue. Are you aware or have any suggestion on what could be the cause?

![Screenshot 2019-04-11 at 20 25 37](https://user-images.githubusercontent.com/1882080/55986879-3d047f00-5c98-11e9-9f02-51426db86882.png)

**Comment by kmahar** [comment]
Hey, thanks so much for reporting this! We're not aware of any particular issue that would be causing this - probably, we are not cleaning up a bson_t somewhere that we should be. Could you possibly give us a code sample that reproduces this?

**Comment by kmahar** [comment]
I think I've found the source, actually. Give me a few minutes and I will put up a patch on a branch for you to test.

**Comment by valeriomazzeo** [comment]
Unfortunately it's not that easy, it may be due to the complex data structure on my types.

>I think I've found the source, actually. Give me a few minutes and I will put up a patch on a branch for you to test.

That's great, I can definitely test that against my project.

**Comment by kmahar** [comment]
I've made the changes on top of the 0.0.9 tag on [this branch](https://github.com/mongodb/mongo-swift-driver/tree/leak) -- let us know how it goes. we'll definitely get these fixes into the next tagged release with Swift 5 support.

re: `BSONEncoder`/`BSONDecoder`, you could encounter some race conditions if you are mutating the same encoder or decoder (i.e. by setting encoding/decoding strategies) while using it in multiple threads. They don't preserve any internal state otherwise though - all the storage/data is local to the `encode`/`decode` functions - so if you're just using those functions it should be safe.

**Comment by valeriomazzeo** [comment]
That's what I thought. I will give it a go now.

**Comment by valeriomazzeo** [comment]
@kmahar it's now better but it seems there are still some coming from the client initialisation method.
![Screenshot 2019-04-11 at 22 10 14](https://user-images.githubusercontent.com/1882080/55993296-9f647c00-5ca6-11e9-8a00-57af04697b5d.png)

**Comment by kmahar** [comment]
@valeriomazzeo just pushed another commit to that branch, try now?
thanks so much for helping us find these - we're planning on doing a full audit of the driver for memory leaks in the coming weeks.

**Comment by valeriomazzeo** [comment]
Thanks @kmahar. It seems they have all been fixed now. I can't see any that relates to the mongo driver.
Another thing which I would be really interested in helping with, is the `BSONEncoder/BSONDecoder` memory usage and performances.

Some of my structures (about 1MB in size) need about 8MB to be decoded. When decoding a lot of them memory usage spikes up at 500MB. Also performance wise it seems very slow.

It would be interesting to understand where the bottleneck is and if it's something to do with my `Codable` implementation or with the `BSONEncoder/BSONDecoder` themselves.

Thoughts?

**Comment by kmahar** [comment]
@valeriomazzeo Glad to hear it - we're actually going to tag a 1.0 release, will have lots of new stuff like improved error reporting, Swift 5, these fixes etc. Just have to get the last couple things through code review and then we will tag it.

We would be glad to have your help with that! One thing that might be helpful in identifying where the problem is coming from is if you could test the comparative memory usage of `JSONDecoder` when decoding the same structs from JSON instead. Our decoder implementation is strongly based on that, so in theory the memory usage should be similar.

**Comment by valeriomazzeo** [comment]
Thanks, I will open a new issue once I have the time to audit `JSONDecoder` and `BSONDecoder` against my data set.

Closing this as it has been fixed by https://github.com/mongodb/mongo-swift-driver/pull/237
