### ISSUE TITLE
Patch release should be backwards compatible?

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#285]
In my package I have defined a flexible dependency to `mongo-swift-driver` to get advantage of patch releases. See: https://github.com/asensei/vapor-fluent-mongo/blob/master/Package.swift#L21

Although, in one of the latest patch releases `0.1.x` some `IndexOptions` fields have been renamed, effectively breaking my package that no longer compiles.

In general, I would expect the following:
- Major: Changes in public API. Let's break everything!
- Minor: New features. Deprecated API. Still backwards compatible.
- Patch: Bugfixes. Definitely backwards compatible.

Taking `IndexOptions` as an example. I would have added `expireAfterSeconds`, deprecated `expireAfter` but still kept that as an alias, and tagged a new minor version.

This obviously is arguable and each team/project has its own rules.
As a user of this library I'd be grateful to know yours. 🤓

**Comment by kmahar** [comment]
Since we are a pre-1.0 library, [semantic versioning rules](https://semver.org/#spec-item-4) say that we are free to change anything at any time.

That said, we realize this unpredictability is not ideal, and our plan from now on while we are pre-1.0 is that for any breaking changes we'll tag a new minor version. So going forward you should be safe to depend on the driver up to the next minor version as you are now.

After we tag 1.0, we'll be following typical semver rules for 1.0+ libraries as you've described above. 🙂 

Thanks for asking and let us know if you have any questions!
