### ISSUE TITLE
Using other types in Documents

### ISSUE THREAD

**Issue by svanimpe** [mongodb/mongo-swift-driver#307]
In my unit tests, I often create complex documents to verify that my objects are encoded in the correct format. These documents often embed other (also `Encodable`) objects. 

As an example, here's a document that includes a simple `URL` and a `ClosedRange`:

```swift
let document: Document = [
    "string": "string",
    "int": 1,
    "url": URL(string: "http://some.url")!,
    "range": 1...3
]
```

Obviously, this doesn't compile because neither `URL` nor `ClosedRange` are `BSONValue`s.

I'm wondering how I can most easily include these embedded objects, without having to write their documents out in full.

I currently use MongoKitten, which includes a `PrimitiveConvertible` protocol for this purpose: https://github.com/OpenKitten/BSON/blob/master/6.0/Sources/BSON/Types/PrimitiveConvertible.swift

This protocol has only one requirement, which I can easily implement for all `Encodable` types as follows:

```swift
extension PrimitiveConvertible where Self: Encodable {

    public func makePrimitive() -> Primitive? {
        return try? BSONEncoder().encodePrimitive(self)
    }
}
```

This lets me use all `Encodable`s (including `URL` and `ClosedRange`) directly in BSON Document.

Can I achieve something similar with MongoSwift or do I need to create a protocol of my own?

**Comment by kmahar** [comment]
Hi @svanimpe!

As of now we haven't built any facilities into the driver to do this for you, though it is something we've discussed in the past. I think introducing a protocol as you've mentioned above is probably your best bet. We've opened a JIRA ticket ([SWIFT-533](https://jira.mongodb.org/browse/SWIFT-533)) about introducing such a protocol in the driver and using that rather than `BSONValue` in our dictionary literal init for `Document`.

One thing I would note about the protocol approach like above is that there's currently no equivalent method to `encodePrimitive`, i.e. our encoder will only give you back a `Document`. 

So to support cases like `ClosedRange` where the top-level container is unkeyed, or cases where the top-level container is a single value container, you will probably need to do something like this in your protocol, where the value to be encoded is wrapped in a struct first:

```swift
struct Wrapper<T: Encodable>: Encodable {
    let value: T
}

func makeBSONValue() -> BSONValue? {
    let wrapper = Wrapper(value: self)
    let encodedWrapper = try? BSONEncoder().encode(wrapper)
    return encodedWrapper?["value"]
}
```

We've also opened [SWIFT-534](https://jira.mongodb.org/browse/SWIFT-534) about adding some way to get behavior like `encodePrimitive` when using the `BSONEncoder`, which would make the wrapper type unnecessary. 

I hope that helps - please let us know if you have any more questions or feature suggestions.

Also, will I see you at Serverside.swift again this year? 🙂

**Comment by svanimpe** [comment]
Thanks, I will keep an eye on this 👍

And yes 😄 (see Slack)

**Comment by kmahar** [comment]
Cool, going to close for now as the work will be tracked on the JIRA tickets. Will post any updates on the tickets here.
