### ISSUE TITLE
Can you provide more examples how to use the driver?

### ISSUE THREAD

**Issue by awadodeh** [mongodb/mongo-swift-driver#337]
Can you provide more examples n how to use the driver:

1. Insert one unique element based on criteria other the _id?
2. Getting one exact element?
3. Getting bulk records based on array of ids ?

**Comment by kmahar** [comment]
Hi @awadodeh, thanks for reaching out.

1. Can you clarify what you mean by "element"? Are you asking how to ensure that a field other than the `_id` field is unique for a collection?

2. Do you mean you want to retrieve a single document from a collection? Or do you only want to retrieve a single field from each document (e.g. all of your documents have both fields "a" and "b" but you only want to get back "a")? 

3. If you want to match any of a number of `_id`s, you can use a `find` with the `$in` operator. See the MongoDB documentation on `$in` [here](https://docs.mongodb.com/manual/reference/operator/query/in/).
For example:
```swift
let client = try MongoClient()
let inventory = client.db("myApp").collection("inventory")
let ids = [1, 2, 3]
let query: Document = ["_id": ["$in": ids] as Document]
let matches = try inventory.find(query)
for match in matches {
    print(match)
}
```
See the documentation for [`MongoCollection.find`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoCollection.html#/s:10MongoSwift0A10CollectionC4find_7options7sessionAA0A6CursorCyxGAA8DocumentV_AA11FindOptionsVSgAA13ClientSessionCSgtKF) and [`MongoCursor`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoCursor.html) for more info.

**Comment by awadodeh** [comment]
> Hi @awadodeh, thanks for reaching out.
> 
> 1. Can you clarify what you mean by "element"? Are you asking how to ensure that a field other than the `_id` field is unique for a collection?
> 2. Do you mean you want to retrieve a single document from a collection? Or do you only want to retrieve a single field from each document (e.g. all of your documents have both fields "a" and "b" but you only want to get back "a")?
> 3. If you want to match any of a number of `_id`s, you can use a `find` with the `$in` operator. See the MongoDB documentation on `$in` [here](https://docs.mongodb.com/manual/reference/operator/query/in/).
>    For example:
> 
> ```swift
> let client = try MongoClient()
> let inventory = client.db("myApp").collection("inventory")
> let ids = [1, 2, 3]
> let query: Document = ["_id": ["$in": ids] as Document]
> let matches = try inventory.find(query)
> for match in matches {
>     print(match)
> }
> ```
> 
> See the documentation for [`MongoCollection.find`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoCollection.html#/s:10MongoSwift0A10CollectionC4find_7options7sessionAA0A6CursorCyxGAA8DocumentV_AA11FindOptionsVSgAA13ClientSessionCSgtKF) and [`MongoCursor`](https://mongodb.github.io/mongo-swift-driver/Classes/MongoCursor.html) for more info.

**Comment by awadodeh** [comment]
Hey Kaitlin, I closed the issue by mistake. 
**Update**:

1. I mean by element a record of a data model. i.e 
I have this model 
```
struct image: Codable {
    public let userID: String
    public let value: String
    public let imageHash: String?

    public init(userID: String, value: String) {
        self.userID = userID
        self.value = value
        self.imageHash = "inital_value"
    }
}
```
Each userID must have one record in my case, I would like to know how can I insert a new record without duplicating.

2. Is there any native method that returns one exact record, in my use case. I would like to get one record in regard to one `userID`?

3. Does this also apply on other attributes of different data models, in my case `userID` ?

Thanks for you help! I really appreciate that!

**Comment by kmahar** [comment]
1. The way MongoDB enforces uniqueness for particular fields is using [unique indexes](https://docs.mongodb.com/manual/core/index-unique/). By default MongoDB will create a unique index on the `_id` field when a collection is created, which is how uniqueness is enforced for that property. If you need uniqueness on the `userID` field as well, you can create a unique index on that.
The index only needs to be created once for the collection, so you may just want to do it in the mongo shell as demonstrated at the link above. 
However, it is also possible to do in the driver:
```swift
let index = IndexModel(keys: ["userID": 1], options: IndexOptions(unique: true))
try myCollection.createIndex(index)
```

Once you do that, the server will raise a duplicate key error if you try to insert a record with a duplicate `userID`.

That said, it is maybe worth considering if your data model allows just using the `userID` for the `_id` field of each document. Otherwise each document in your collection will contain two separate unique keys, `_id`, and `userID`.
If you want the property to be named `userID` in your struct you could use `CodingKeys` to customize the names, e.g.
```swift
enum CodingKeys: String, CodingKey {
    case userID = "_id", value, imageHash
}
``

2. We don't have a `findOne` method, though this does exist in some other MongoDB drivers, so I've opened a JIRA ticket proposing we add such a method: https://jira.mongodb.org/browse/SWIFT-643
In the meantime the way to accomplish this is by performing a `find` with a `limit` of `1`:
```swift
let images = try db.collection("images")
let cursor = try images.find(["userID": "Kaitlin"], options: FindOptions(limit: 1))
let results = Array(cursor)
guard !results.isEmpty else {
    // handle case with no match
}

let match = allResults[0]
```

3. Yes, you could similarly use `$in` with any other attribute.

**Comment by awadodeh** [comment]
This worked like a charms as well!!!
Thanks for the fast response and the great details!
