### ISSUE TITLE
Swift Package file for Vapor

### ISSUE THREAD

**Issue by jonny7** [mongodb/mongo-swift-driver#452]
Hi @kmahar 

Thanks for this driver, it looks great. For Vapor v4, it now requires 5.2 and a platform specification of `.macOS(.v10_15)`.

So a more appropriate declaration for Vapor 4 would be the following, I just based mine of the API template.
```swift
// swift-tools-version:5.2
import PackageDescription

let package = Package(
    name: "app",
    platforms: [
       .macOS(.v10_15)
    ],
    products: [
        .executable(name: "Run", targets: ["Run"]),
        .library(name: "App", targets: ["App"]),
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.2.1"),
        .package(url: "https://github.com/mongodb/mongo-swift-driver", .upToNextMajor(from: "1.0.0-rc0"))
    ],
    targets: [
        .target(name: "App", dependencies: [
            .product(name: "MongoSwift", package: "mongo-swift-driver"),
            .product(name: "Vapor", package: "vapor"),
        ]),
        .target(name: "Run", dependencies: [
            .target(name: "App"),
        ]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ])
    ]
)

```
I realize from the other issues that it currently doesn't build with 5.2. These are my errors, for reference.

![image](https://user-images.githubusercontent.com/6732997/79499079-c7e12d80-8000-11ea-93bb-7ca8b4e8fe83.png)

I can make a PR for the package.swift if required and adjust to fit your structure if wanted

Thanks 😄

**Comment by kmahar** [comment]
Hi @jonny7 thanks for reaching out! 

We would be happy to accept a PR updating the Vapor example to use Vapor 4.0.0 - I hadn't had a chance to do that since it was released.

I believe the errors you're getting there are actually not related to 5.2, but to what's described in #387, a bug with Xcode's SwiftPM integration. (The 5.2 issue only applies to driver version 0.2.0 and below.)
If you use `swift package generate-xcodeproj` to generate an `.xcodeproj` for the example project and then open that in Xcode I think it should build OK.

**Comment by jonny7** [comment]
Great, I'll add that PR now, yeah I missed that PR but saw the other one. I'll add now! 😄
