### ISSUE TITLE
Nimble version set as `exact(8.0.2)`

### ISSUE THREAD

**Issue by GRiMe2D** [mongodb/mongo-swift-driver#462]
Can we remove this exact version pinning for `Quick/Nimble`.

We use the same project for testing and it is creating a conflict with the project.
https://github.com/mongodb/mongo-swift-driver/blob/8fd44764b33c32473afb67d38b6f63d1865fd996/Package.swift#L10

Our `Package.swift` declares it like `from("8.0.7")` and command `swift package update` hangs indefinitely.

The workaround was to downgrade our declaration as `from("8.0.2")`

**Comment by kmahar** [comment]
Hi @GRiMe2D, thanks for reaching out!

I believe we did this before because we were having issues running our tests when 8.0.3 was the latest Nimble release. It seems to be fixed in the newer patch versions.

I've updated our dependency in 0764687226c400ae7c3958d89718124cd8a4d5c7 to allow any Nimble version with major version 8. Does this solve your issue?

**Comment by GRiMe2D** [comment]
Hi @kmahar, thanks for fast reply and fix. I can confirm that it resolves my issue.

**Comment by kmahar** [comment]
Great! Closing this issue then, please feel free to reach out with anything else you run into.
