### ISSUE TITLE
[Question] Is there an equivalent of BsonIgnoreIfNullAttribute?

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#495]
I am having this very same problem: https://stackoverflow.com/questions/9917804/update-with-addtoset-not-updating-null-value-with-mongodb-c-sharp

I wonder whether there's an equivalent of `BsonIgnoreIfNullAttribute` that can be used in the swift driver and if so, how to use it.

https://api.mongodb.com/csharp/1.1/html/351f430e-5f7f-d97e-02e5-81b4f9c37d3f.htm

**Comment by kmahar** [comment]
Hi @valeriomazzeo, thanks for reaching out.

Could you clarify how the data containing the nulls is being inserted into the database? e.g. are you creating a document from JSON and inserting that? Or using `BSONEncoder` to a turn a struct into a document?
If the latter (which seems to be most equivalent to the C# issue linked), the encoder should by default already just omit any struct properties that are set to `nil`.

**Comment by kmahar** [comment]
if I understand correctly, you have a collection in the DB with data something like this:
` {"_id": 123, "someArrayProperty": null}` or in Swift `["_id": 123, "someProperty": .null]`.

And what you are running into is trying to perform an update with a document like like `["$addToSet": ["someProperty": 1]]` which fails. 

So ideally the initial document would have just been inserted as `["_id": 123]` which would make the server accept the `$addToSet` call as the field would be missing rather than being a different BSON type.

Right now there is no processing in the driver of a `Document` by us when you insert it - the document already wraps raw bytes, so there's no further serialization step. So I think in this case your best bets would be to either update your code that creates the `Document` to ignore `.null`s, or to strip out the `.null`s manually before calling `insertOne`/`insertMany`/`bulkWrite`. 

I believe the C# option `BsonIgnoreIfNullAttribute` relates to how the driver serializes custom types to documents via their equivalent of `BSONEncoder`. We do already have the equivalent behavior in our encoder by default, but I don't think it helps here if you are directly creating `Document`s without the encoder.

**Comment by valeriomazzeo** [comment]
>if I understand correctly, you have a collection in the DB with data something like this:
{"_id": 123, "someArrayProperty": null} or in Swift ["_id": 123, "someProperty": .null].
>
>And what you are running into is trying to perform an update with a document like like >["$addToSet": ["someProperty": 1]] which fails.
>
>So ideally the initial document would have just been inserted as ["_id": 123] which would make the server accept the $addToSet call as the field would be missing rather than being a different BSON type.

That's correct.

>Right now there is no processing in the driver of a Document by us when you insert it - the document already wraps raw bytes, so there's no further serialization step. So I think in this case your best bets would be to either update your code that creates the Document to ignore .nulls, or to strip out the .nulls manually before calling insertOne/insertMany/bulkWrite.

Yes, that's what I am trying to do, although not ideal.

>I believe the C# option BsonIgnoreIfNullAttribute relates to how the driver serializes custom types to documents via their equivalent of BSONEncoder. We do already have the equivalent behavior in our encoder by default, but I don't think it helps here if you are directly creating Documents without the encoder.

I must be missing something, what's the other way of doing it? I am not using JSON, but at the same time I don't have pre-defined data types so I am creating `Document`s and then passing them to `BSONEncoder`. Although, that doesn't seem to strip out the `null` fields. Is there a better way?

**Comment by kmahar** [comment]
The other way (where it would help) is if you were using pre-defined data types. What form do you receive the data from Fluent in?

The purpose of the encoder is for some Swift type -> document conversion, mainly useful for users who are using a `MongoCollection<T>` where `T` is some custom type matching up with their collection's schema. But since the output type of `BSONEncoder.encode` is a `Document`, we don't actually do anything when you pass in a `Document`: https://github.com/mongodb/mongo-swift-driver/blob/8fd44764b33c32473afb67d38b6f63d1865fd996/Sources/MongoSwift/BSON/BSONEncoder.swift#L143-L144

**Comment by valeriomazzeo** [comment]
The fluent value is a DatabaseQuery.Value, at the moment I am converting it like this https://github.com/asensei/vapor-fluent-mongo/blob/feature/swift5.2/Sources/FluentMongo/DatabaseQueryValue%2BMongo.swift#L20

Although it’s possible to try and `$unset` fields containing `null` on updates and stripping such fields entirely on insert. There are other side effects in fluent. 

The real issue that I would like to solve is to avoid that $addToSet error altogether when the field is null. If I understood correctly that BsonIgnoreIfNullAttribute is only at the driver level? If so how does it work? Does it sends two commands to the server? One that sets the field to an empty array followed by $addToSet?

Can mongo for swift provider such feature or shall I implement it myself?

**Comment by kmahar** [comment]
Is it possible to just return `nil` in the `.null` case there, or do you need to be able to differentiate between unset fields and a field with a value of BSON null?

**Comment by valeriomazzeo** [comment]
Yes, I have a branch that does that. I am not sure it’s possible to make that distinction with Fluent.

A possible solution is on inserts to return nil so that the key is not added. On updates it has to $unset fields that contains .null, current implementation only use $set at the moment.

In order to achieve that on updates I need to iterate twice through all the nested structure to separate fields in $set and $unset groups.

It does feel a bit overkill especially because it was somehow elegant to only use $set, which would be fine if it wasn’t for those array update operators. In fluent, when .null, I can handle those values either as the fields are always unset, or are always null. The latter won’t work because of $addToSet, $pullAll, etc. The former It’s a bit weird but maybe is somehow the preferred mongo way?

**Comment by valeriomazzeo** [comment]
Closing as it has been clarified that `BSONEncoder` already achieve such functionality although is bypassed when encoding a `Document` directly.
