### ISSUE TITLE
Use the $in operator with a regular expression

### ISSUE THREAD

**Issue by valeriomazzeo** [mongodb/mongo-swift-driver#517]
I am trying to write a filter document that uses a regex pattern inside `$in` as described [here](https://docs.mongodb.com/manual/reference/operator/query/in/#use-the-in-operator-with-a-regular-expression).

```
db.inventory.find( { tags: { $in: [ /^be/, /^st/ ] } } )
```

Unfortunately, I can't find a way to describe a regex pattern as a `BSON`. Using `string` adds double quotes and causes the query value not to be recognized as a regex pattern. I know I could use `$regex` but I am specifically trying to use a regex pattern in `$in` and as per documentation `$in` can't contain `$regex`, only a `/pattern/`.

**Current behaviour**

```swift
let filter: Document = ["tags": [ "$in": .array[.string("/^be/"), .string("/^st/")] ] ]
```

The above filter is encoded as:
```json
{ "tags": { "$in": [ "/^be/", "/^st/" ] } }
```

**Expected behaviour**
Either `/pattern/` should be detected and processed accordingly or BSON should have a way to inject such type. I.e. `.pattern("/^be/")`
```json
{ "tags": { "$in": [ /^be/, /^st/ ] } }
```

**Comment by kmahar** [comment]
Hi @valeriomazzeo, you can accomplish this by using the `BSONRegularExpression` type in your query document as follows:

```swift
let regex1 = BSONRegularExpression(pattern: "^be", options: "")
let regex2 = BSONRegularExpression(pattern: "^st", options: "")
let filter: BSONDocument = [ "tags": ["$in": [.regex(regex1, regex2)]] ]
```

The slashes at the start/end are not needed in this case, those are just how Javascript handles delimiting regexes.

Let me know if that works for you.

**Comment by valeriomazzeo** [comment]
I tried that and the output is:
```json
{
  "tags" : { "$in" : [ { "$regularExpression" : { "pattern" : "^be", "options" : "" } } ] }
}
```
I thought that wouldn't work because compass gives me this error:
```
cannot nest $ under $in
```

But actually running my unit tests in Swift they all pass. 🤔

**Comment by kmahar** [comment]
So this is a bit tricky. 

When you print out a document in the driver, we show you the ["relaxed" extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/) representation of it.

A regular expression's representation in extended JSON is:
`{ "$regularExpression" : { "pattern" : "^be", "options" : "" } }`

i.e. a document with another document nested in it. However, that's not actually how that type is stored in in a document - we don't create a nested document with these values, we just directly store that data type in the bytes.

If you paste that extended JSON into Compass (or the MongoDB shell), it will interpret it as an actual document with that structure, rather than parsing the extended JSON into an equivalent document.

For many types (like integers, strings) the relaxed extended JSON representation of a BSON type (e.g. a number) is equivalent to the Javascript representation of it that Compass and the MongoDB shell use, but it doesn't always match up. Regexes are one type where it differs, where Compass and the shell use the `/^be/` representation but extended JSON does not.

**Comment by valeriomazzeo** [comment]
I see, that's what tricked me. Maybe it would be useful to have also a javascript representation for debugging purposes?

**Comment by kmahar** [comment]
We could consider that, though IMO it would be better for all of our tooling (including Compass) to support extJSON querying as its designed to be a portable, language-independent format for representing documents. Compass does already support it in other contexts e.g. you can insert extJSON documents, but the query bar does not.
Rather than all of our drivers adding support for a second format, it would be better and easier for Compass to support the first format.
This has been discussed on [COMPASS-3081](https://jira.mongodb.org/browse/COMPASS-3081) as well as this [suggestion](https://feedback.mongodb.com/forums/924283-compass/suggestions/40471285-as-a-developer-using-extended-json-strict-mode-que) on the MongoDB feedback engine.
