### ISSUE TITLE
SWIFT-1051 ⁃ [MemoryLeak] [Linux] Massive memory consumption on encoding

### ISSUE THREAD

**Issue by NikolayJuly** [mongodb/mongo-swift-driver#571]
## Information
I see this issue only if I use this driver on linux in docker container. And I don't think this is issue of a container or my code, will provide more evidence below

I believe this driver is designed to be used on server, which mean it most likely will be used in swift container. 

### Swift version

I'm using docker container swift:bionic-5.3.2, and also checked slim version.

### Driver version

swift driver: 1.0.1
mongo-c-driver: 1.16

## What is the problem? 

This lines are leaking
```
let decoder = BSONDecoder()
decoder.dateDecodingStrategy = .bsonDateTime
return try decoder.decode(SomeCodable.self, from: BSONDocument)
```

I attached sample code as zip: 
[EmptyVaporImageToZip.zip](https://github.com/mongodb/mongo-swift-driver/files/5803300/EmptyVaporImageToZip.zip)

this is small project, which only do Decoding. I don't do 200k codings in a row usually, this is just for test purpose. 
This is how I'm using it: I'm getting BSONDocument from collection and using `BSONDecoder` to decode into my objects. Looks like proper usage. Let me know if I'm doing it wrong.

If you run it in container - you will get massive memory usage - **467MB**.  Info I'm getting using `docker stats`
Alternatively there is native encoding - which use only **2MB** to encode the same amount of objects.
As result service which uses this driver restart really often and the more API calls I have, the more ofter service restarts.

This difference in footprint lead me to idea that this is issue of a driver rather than my code. 
Easy switch can be done in `main.swift` line 11 or 12. Comment/uncomment one of them

## Reproducing the bug
Build on macOS to see that there is no so big issue
1. Open zip
2. Generate project with `swift package generate-xcodeproj`
3. Run app. You will see that memory jumps, which is fine. Cos native one doing things close to it.

Reproduce issue in linux container:
1. You need build container with `docker build --no-cache -t empty-service-image-build -f ./AnalyticsServiceBuildImage.dockerfile ./` . You can see that container is basic - install mongo driver and build swift app on top
2. Run container using `docker run empty-service-image-build `
3. Run `docker stats` to see mem usage. With BSONEncoder you see huge memory footprint(400+MB). You can switch to native decoding and see desired foot print (~2MB)

**Comment by NikolayJuly** [comment]
I decided to check with newer mongo-c-driver. I checked out 1.17.3 and issue is still there.

**Comment by kmahar** [comment]
@NikolayJuly Thanks so much for reaching out and provided detailed steps to reproduce this. This is certainly concerning, we are going to look into this and get back to you as soon as we can.

Just to clarify: the driver now uses a vendored copy of libmongoc (not a system-installed one); did you vendor a new libmongoc version into the driver's source code using the vendoring script, or just update the system one?

**Comment by NikolayJuly** [comment]
Before compile this driver I install manually libmongoc (as you can see in dockerfile). I will try now build without manually install.

**Comment by NikolayJuly** [comment]
I just removed install lines of libmongoc and I can confirm that it works fine. I indeed see that there is compilation of driver anyway in logs. You saved me sometime in build docker image step. Thanks.
But issue with memory leak is still there. 

But I assume I still need install manually `libssl-dev` and `zlib1g-dev`?  for driver inside of swift mongo driver, right?
I updated dockerfile, by removing manual libmongoc driver install
[EmptyVaporImageToZip.zip](https://github.com/mongodb/mongo-swift-driver/files/5803738/EmptyVaporImageToZip.zip)

**Comment by kmahar** [comment]
Yes, on Linux installing those system libraries manually is required for the time being, since libmongoc relies on them.

Thank you for the updated .zip file! I will get back to you shortly once I've had a chance to investigate.

**Comment by kmahar** [comment]
Hi @NikolayJuly, I've found the source of the leak and released a fix in v1.0.2 of the driver. From my testing, this brings the memory usage of your example project in line with `JSONDecoder`, but please confirm that this has resolved the issue on your end.

It turns out that we were calling a Foundation method `String.cString(using:)` which has a longstanding memory leak in its Linux implementation.

Thank you again for the very detailed bug report, and please let us know if you have any further questions or issues 🙏

**Comment by NikolayJuly** [comment]
It is 1am in London, but let me do a quick test.
Btw, I saw this leak on macOS as well. But leas was much smaller, it leak only key, not whole json object. And I assumed it is only macOS, cos it lead to NSString compatibility and ObjC runtime

**Comment by NikolayJuly** [comment]
I can confirm, that memory usage was down to same level as native decoding: ~2MB. Thank you very much! 👍

**Comment by kmahar** [comment]
Great to hear!

Regarding macOS, interesting, I think the macOS leak you saw may be the same underlying issue as one of those discussed in #516. The string returned from the `cString` is supposedly autoreleased on Apple platforms. I am not familiar with how that works, but perhaps it is either leading to a leak or the appearance of a leak anyway.

I think that leak may have the same cause as one of those described in #516. I was never able to reproduce that one myself on macOS, but I had a [suspicion](https://github.com/mongodb/mongo-swift-driver/issues/516#issuecomment-675739637) the leak was coming from this cString method due to the stack traces. I did not realize until today that method had known issues on Linux as well.

**Comment by NikolayJuly** [comment]
<img width="1206" alt="Screenshot 2021-01-13 at 01 47 19" src="https://user-images.githubusercontent.com/699116/104395789-63c4a900-5541-11eb-9f42-00ebd34dc0e1.png">

I have a huge profiler report for 2.2GB. This is image from it. pointing to the same `cString` but as you can see, memory leak/lost was KBs, not MBs. So I just ignored it.

**Comment by NikolayJuly** [comment]
@kmahar I also have a question, on how you profile on linux? I'm quite good with profiling apps with xcode on macOS, but never tried to do it on linux. Thats why I only pointed to memory usage, rather than some profiler results. What did you used to find this leak?

**Comment by kmahar** [comment]
Ah I see, thank you for the screenshot.

Re profiling on Linux: first I updated your program a bit so that it would terminate upon completing of the decoding calls. I then followed the steps described [here](https://github.com/swift-server/guides/blob/master/memory-leaks.md#debugging-leaks-with-leak-sanitizer) to run that using the address sanitizer, which detects leaks, and symbolicate the resulting output using `addr2line`. This pointed me directly to the `_bytesInEncoding` method where the [leak occurs](https://github.com/apple/swift-corelibs-foundation/blob/14893a089982a08c65a961f79c9a2114d059827f/Sources/Foundation/NSString.swift#L197).

You can also use Valgrind as described on that link, though apparently it can have some false positives.

**Comment by NikolayJuly** [comment]
Thank you, I will use it next time, I have issue on linux specifically.
